# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jekyll-remote-theme


# Site settings
email: george.hall@ucl.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ghall.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: G_T_Hall
github_username:  george-hall-ucl
title: 'George Hall'
description: 'This is my new website'
permalink: pretty
logo: "https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=gBlYdZwAAAAJ&citpid=3"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
